spring:
  data.mongodb:
    uri: mongodb://mongo-moment:27017/footprint
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
eureka:
  instance:
    hostname: org-service
    appname: org-service
    instance-id: org-service:${random.uuid}
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}   
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-service:30381/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS 
feign:
  client:
    config:
      user-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
